script:
- |
  npm i
  npm run build
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  fqdn: faucet.vecha.in
  local-dir: dist
  on:
    branch: master
